fix: path_to_module to handle hidden files (e.g. .clang-tidy) correctly (#987)
It works fine with normal install `pip install .` but not for editable
install `pip install -e .`

I got the error below without this fix because it can't handle hidden
file's extension corretly:
```
    File "/opt/miniconda3/envs/pyapl/lib/python3.12/site-packages/scikit_build_core/build/_pathutil.py", line 31, in path_to_module
      path = path.with_name(path.name.split(".", 1)[0])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/miniconda3/envs/pyapl/lib/python3.12/pathlib.py", line 634, in with_name
      raise ValueError("Invalid name %r" % (name))
  ValueError: Invalid name ''
```
For example, if it's `.clang-tidy`, the original splitting
`path.name.split(".", 1)[0]` results empty string.

---------

Signed-off-by: Henry Schreiner <henryschreineriii@gmail.com>
Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Co-authored-by: Henry Schreiner <henryschreineriii@gmail.com>